
import React, { useState, useEffect, useCallback } from 'react';
import { Page } from '../../types';
import LevelLayout from '../LevelLayout';
import GameEndScreen from '../GameEndScreen';
import GaborEmoji from '../GaborEmoji';
import { EMOJI_GRID_L4, TARGET_SCORE_L4 } from '../../constants';

interface Level4Props {
  setCurrentPage: (page: Page) => void;
  saveLevelCompletion: (levelId: string, isCompleted: boolean) => void;
}

const START_FONT_SIZE = 60;
const END_FONT_SIZE = 16;
const FONT_SIZE_DECREMENT = (START_FONT_SIZE - END_FONT_SIZE) / (TARGET_SCORE_L4 - 1);

const START_CONTRAST = 1.0;
const END_CONTRAST = 0.3;
const CONTRAST_DECREMENT = (START_CONTRAST - END_CONTRAST) / (TARGET_SCORE_L4 - 1);

const GRID_SIZE = 100; // 10x10 grid

const Level4: React.FC<Level4Props> = ({ setCurrentPage, saveLevelCompletion }) => {
  const [currentEmoji, setCurrentEmoji] = useState<string>('');
  const [correctIndex, setCorrectIndex] = useState(0);
  const [correctClicks, setCorrectClicks] = useState(0);
  const [incorrectClicks, setIncorrectClicks] = useState(0);
  const [gameState, setGameState] = useState<'playing' | 'finished'>('playing');

  const currentFontSize = Math.max(END_FONT_SIZE, START_FONT_SIZE - correctClicks * FONT_SIZE_DECREMENT);
  const currentContrast = Math.max(END_CONTRAST, START_CONTRAST - correctClicks * CONTRAST_DECREMENT);
  
  const generateNewRound = useCallback(() => {
    const randomEmoji = EMOJI_GRID_L4[Math.floor(Math.random() * EMOJI_GRID_L4.length)];
    const newCorrectIndex = Math.floor(Math.random() * GRID_SIZE);

    setCurrentEmoji(randomEmoji);
    setCorrectIndex(newCorrectIndex);
  }, []);

  useEffect(() => {
    if (gameState === 'playing') {
      generateNewRound();
    }
  }, [gameState, correctClicks]); // Rerun on correctClicks to get a new layout

  const handleEmojiClick = (isCorrectChoice: boolean) => {
    if (gameState !== 'playing') return;

    if (isCorrectChoice) {
      const newCorrectClicks = correctClicks + 1;
      setCorrectClicks(newCorrectClicks);

      if (newCorrectClicks >= TARGET_SCORE_L4) {
        const success = incorrectClicks === 0;
        saveLevelCompletion('level4', success);
        setGameState('finished');
      } else {
        // New round is generated by useEffect
      }
    } else {
      setIncorrectClicks((prev) => prev + 1);
    }
  };
  
  const resetLevel = () => {
    setCorrectClicks(0);
    setIncorrectClicks(0);
    setGameState('playing');
  };

  const renderGame = () => {
    if (gameState === 'finished') {
      return (
        <GameEndScreen
          isSuccess={incorrectClicks === 0}
          correctCount={correctClicks}
          incorrectCount={incorrectClicks}
          onNextLevel={() => setCurrentPage('level5')}
          onReset={resetLevel}
        />
      );
    }

    return (
      <div className="grid grid-cols-10 w-full max-w-3xl aspect-square mx-auto p-1 gap-1">
        {Array.from({ length: GRID_SIZE }).map((_, index) => (
             <GaborEmoji
                key={`${correctClicks}-${index}`} // Add correctClicks to key to force re-render
                hasGaborPatch={index === correctIndex}
                contrast={currentContrast}
                fontSize={currentFontSize}
                onClick={() => handleEmojiClick(index === correctIndex)}
                className="w-full h-full flex items-center justify-center"
            >
                {currentEmoji}
            </GaborEmoji>
        ))}
      </div>
    );
  };
  
  return (
    <LevelLayout levelId={4} setCurrentPage={setCurrentPage}>
      <div className="w-full flex-grow flex items-center justify-center min-h-0">
        {renderGame()}
      </div>
       {gameState === 'playing' && (
        <div className="shrink-0 flex justify-center space-x-2 sm:space-x-4 my-2 w-full max-w-xs sm:max-w-sm">
            <div className="bg-cyan-600 text-white p-2 sm:p-3 rounded-lg shadow-md flex-1 text-center font-bold text-sm sm:text-lg">Score: {correctClicks}/{TARGET_SCORE_L4}</div>
            <div className="bg-rose-500 text-white p-2 sm:p-3 rounded-lg shadow-md flex-1 text-center font-bold text-sm sm:text-lg">Incorrect: {incorrectClicks}</div>
        </div>
      )}
    </LevelLayout>
  );
};

export default Level4;